### ISSUE TITLE
$params arg in Dewdrop\Admin\Page\Stock\Edit has changed from array to object somehow

### ISSUE THREAD

**Issue by cornelisonc** [DeltaSystems/dewdrop#44]
Catchable fatal error: Argument 2 passed to Dewdrop\Admin\ResponseHelper\Standard::redirectToAdminPage() must be of the type array, object given, called in vendor/deltasystems/dewdrop/Dewdrop/Admin/Page/Stock/Edit.php on line 122 and defined in vendor/deltasystems/dewdrop/Dewdrop/Admin/ResponseHelper/Standard.php on line 122

**Comment by darbyfelton** [comment]
Could you please add the minimal amount of context needed to reproduce the issue? That is, under what circumstances does the issue occur?
