### ISSUE TITLE
Support Additional DB Field Types

### ISSUE THREAD

**Issue by bravadomizzou** [DeltaSystems/dewdrop#47]
Is this something we can add support for?

Dewdrop\Exception: The PostgreSQL 'float4' type is currently not supported. in /project-path/vendor/deltasystems/dewdrop/Dewdrop/Db/Driver/Pdo/Pgsql.php on line 584

**Comment by bravadomizzou** [comment]
float8 seems to work

**Comment by griffbrad** [comment]
In what context are you using the float type in Postgres?
