### ISSUE TITLE
Return to page 1 of results when filtering changed

### ISSUE THREAD

**Issue by stevepowell2000** [DeltaSystems/dewdrop#77]
Say you have a tabular list of data that is paginated across 50 pages.
Now I apply a filter to that data..perhaps creation date > 1/1/2005. This yields 30 pages of data. 
Next I click thru the content and end up on page 28.  I notice something thre and maybe want to apply another filter. So I add another filter. perhaps quantity > 1.
Doing this yields 6 pages of data. but the screen appears blank because it thinks I'm still on page 28.

I would expect to be returned to the first page of the results when I change the filter.  Column sorting should remain as is, but staying on page 28 would yield unexpected results.

**Comment by griffbrad** [comment]
Fixed in 1.6.4.
