### ISSUE TITLE
error when throwing an error when determining activity log entry type

### ISSUE THREAD

**Issue by stevepowell2000** [DeltaSystems/dewdrop#79]
There is an error when throwing an error.
Catchable fatal error: Object of class Dewdrop\ActivityLog\Handler\TableHandler could not be converted to string in .../zend/vendor/deltasystems/dewdrop/Dewdrop/ActivityLog/Entry.php on line 48

https://github.com/DeltaSystems/dewdrop/blob/530e055ddb72e7429fcc808723f11bce05fc9401/Dewdrop/ActivityLog/Entry.php#L48

not sure if this should be 
throw new EntityNotFound("Could not find {$handler->getName()} entity with ID of {$id}");
or
throw new EntityNotFound("Could not find {$handler->getFullyQualifiedName()} entity with ID of {$id}");

**Comment by griffbrad** [comment]
https://github.com/DeltaSystems/dewdrop/commit/74b530314d28f77eca5fcf2868b4d9a7f1da8881
