### ISSUE TITLE
Import Label missing on fields

### ISSUE THREAD

**Issue by bravadomizzou** [DeltaSystems/dewdrop#84]
On boolean fields, there is no immediately visible label on the import-map-fields page. 

Looks to be because they this returns false on those fields. https://github.com/DeltaSystems/dewdrop/blob/master/Dewdrop/View/Helper/BootstrapForm.php#L360

Screen of 2 fields with no labels:
<img width="520" alt="screen shot 2016-06-08 at 5 51 49 pm" src="https://cloud.githubusercontent.com/assets/1663615/15933061/c8dddf18-2e23-11e6-9595-1e46ab242161.png">

**Comment by griffbrad** [comment]
Fixed in 1.16.1.
