### ISSUE TITLE
Add HTTPS support for reset password email link

### ISSUE THREAD

**Issue by bravadomizzou** [DeltaSystems/dewdrop#87]
The link you get (in the email) when you reset your password looks like this:

http://demo.thegraduationcenter.com:443/ and the browser says it is a bad request

**Comment by darbyfelton** [comment]
Good catch! I had added HTTP support for other ports than 80 in to handle my host port mapping to my Vagrant instance, but I didn't add support for HTTPS at the same time.

Here is the relevant code: https://github.com/DeltaSystems/dewdrop/blob/master/Dewdrop/Auth.php#L203

**Comment by darbyfelton** [comment]
I believe this is resolved with https://github.com/DeltaSystems/dewdrop/releases/tag/1.23.0
